$(document).ready(function(){
  	$('.web').hide();
  	$("#home").show();
  	$('.nav_home').click(function(){
  		$('.nav').removeClass("active");
  		$('.web').hide();
  		$("#home").show();
  		$('.nav_home').addClass("active");
  	});
	$('.nav_AB').click(function(){
  		$('.nav').removeClass("active");
  		$('.web').hide();
  		$("#about_us").show();
  		$('.nav_AB').addClass("active");
  	});
  	$('.nav_AH').click(function(){
  		$('.nav').removeClass("active");
  		$('.web').hide();
  		$("#adoption_house").show();
  		$('.nav_AH').addClass("active");
  	});
  	$('.nav_CU').click(function(){
  		$('.nav').removeClass("active");
  		$('.web').hide();
  		$("#contact_us").show();
  		$('.nav_CU').addClass("active");
  	});
  	$('.nav_cats').click(function(){
  		$('.nav').removeClass("active");
  		$('.web').hide();
  		$("#cats_main").show();
  		$('.nav_cats').addClass("active");
  	});
  	$('.nav_QA').click(function(){
  		$('.nav').removeClass("active");
  		$('.web').hide();
  		$("#QA").show();
  	});
  	$('.btn_sign_up').click(function(){
  		$('.nav').removeClass("active");
  		$('.web').hide();
  		$("#SignUp").show();
  	});
  	$('.btn_sign_in').click(function(){
  		$('.nav').removeClass("active");
  		$('.web').hide();
  		$("#SignIn").show();
  	});
  	$('.btnEditProfile').click(function(){
  		$('.btn').removeClass("active");
  		$('.page').hide();
  		$("#ProfileUpdate").show();
  		$("#userName").focus();
  		$('.btnEditProfile').addClass("active");
  	});
  	$("#btnSubmit").click(function(){
  		$('.btn').removeClass("active");
  		$('.page').hide();
  		$("#Profile").show();
  		$('.btnProfile').addClass("active");
  	});
  });
  function SignOut(){
    firebase.auth().signOut();
    console.log('LogOut');
    $('.page').hide();
    $("#home").show();
    $message.html('');
    return true;
  }
